coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0        #do not fail PR, just show warning
    patch:
      default:
        target: 80%
        threshold: 0        #do not fail PR, just show warning

ignore:
  - "tests/"
  - "**/*.config.js"
